/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/Home copy 2.vue')['default']
    Cards: typeof import('./src/components/Cards.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ModalForm: typeof import('./src/components/ModalForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    UserDelete: typeof import('./src/components/UserDelete.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    UserTable: typeof import('./src/components/UserTable.vue')['default']
  }
}
